theme: minima
title: Absurdities
author: pedroluis73
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Absurdties done while coding, doing math or thinking in general by an incorrigible bastard!

# social links
twitter_username: your-twitter-handle
github_username:  pedroluis73

show_excerpts: true # set to false to remove excerpts on the homepage
